### ISSUE TITLE
where can I  find the base images for these labs?

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#1]
I have looked in MCT LDC and also looked for MSlabs scripts but see none. 
where do I get the files and instructions to build the correct environment for the lab steps?

Thanks

**Comment by TJGitHubUser** [comment]
Build guides and base images are not available on the MCT LDC. My understanding is that MCTs can request access to the Lab environment from the Learning Partner.
