### ISSUE TITLE
en-dashes

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#10]
Several of the PowerShell code blocks have en-dashes instead of hyphens, which means that copying and pasting into the lab machines is not working.

In the markdown viewer here in the web browser you can see the difference. The correct hyphens are coloured red by the `powershell syntax-colouring but the en-dashes are black.

One of the authors needs to open the markdown and do a search and replace.

For example, lab 09, exercise 1, task 1, step 5.

   ```powershell
   New-PSDrive –Name 'X' –PSProvider FileSystem –Root '\\SEA-ADM1\Labfiles'
   ```

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. These will be added to list of things to address.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by TJGitHubUser** [comment]
Closed per Moc lab review
