### ISSUE TITLE
Docker search microsoft returns 500 error

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#11]
# Module: 05
#### Step: 04

Description of issue

the command "docker search microsoft" returns a 500 error.

Repro steps:

Complete lab up to this step to repro issue

If you do "docker  search nanoserver" you get some results but I don't think that is the intention of the step. 

Has there been a back end change made to the microsoft repository on docker site?

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by craigbeeremct** [comment]
I get the error message often, both on lab machines from Skillable and on virtual machines hosted locally. It is a bit intermittant though - sometimes the command works.

It appears to be DNS related. Posts on the Internet suggest setting DNS server to 8.8.8.8 or entering FQDNs into hosts.

[https://stackoverflow.com/questions/46036152/lookup-registry-1-docker-io-no-such-host](https://stackoverflow.com/questions/46036152/lookup-registry-1-docker-io-no-such-host)
[https://github.com/docker/for-win/issues/4884](https://github.com/docker/for-win/issues/4884]

**Comment by dvimacedo** [comment]
Instructions have been updated and issue doesn't exist anymore.
