### ISSUE TITLE
step missing to add dhcp extension to WAC

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#12]
# Module: 07
#### Step: 14

Description of issue
Refresh the Microsoft Edge page back on the sea-svr1.contoso.com page, in the Tools list, select DHCP, and then, in the details pane, select Install to install the DHCP PowerShell tools.

Note: If the DHCP entry is not available in the Tools list for sea-svr1.contoso.com, refresh the Microsoft Edge page and try again.

DHCP was not installed by default in my 2110 WAC deployment and I had to manually add the extension.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review solved this issue with pull request #18.
