### ISSUE TITLE
Remote Domain Controller Installation/Promotion Fails

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#13]
# Module: 01
#### Step: 22

When executing the command in Task 2 Step 22, the remote Install-ADDSDomainController command fails with an error. Removing the "-Force:$true" parameter allows the command to execute successfully. 

Repro steps:

1. Follow given instructions through Task 2 Step 22

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by TJGitHubUser** [comment]
Closed per MOC lab review
