### ISSUE TITLE
Lab 3:  Three minor issues

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#2]
## Lab/Demo: 03

**Lab 3, Exercise 1, Task 2, Step 1:** In most all cases, immediately after the install of the .msi, we rec'v error 'ERR_Connection_Refused' and waiting does not rectify this.  There may be a more technical solution but if one reboots SEA-ADM1, it always corrects for this issue. May wish to include this in instructions for any all labs (besides this one) that also have student installing the latest msi. 

**Lab 3, Exercise 1, Task 2, Step 7:**  instructions reference  _sea-svr1.contoso.com_ but per the manifest this VM is not supposed to be in this lab.  Given context of later instructs, this is probably meant to be _sea-dc1.contoso.com_ instead.

**Lab 3, Exercise 1, Task 4, Step 8:** Instruction says '_Do not ask again me again for connections to this computer_', but phrasing is actually '_Automatically connect with the certificate presented by this machine_'

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. We'll look into these and address as appropriate.

**Comment by TJGitHubUser** [comment]
Fixed all three issues, lab and LAK where appropriate.
