### ISSUE TITLE
Storage Migration Service inventory fails

### ISSUE THREAD

**Issue by J-O-S-H-C** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#28]
# Module: 05: Implementing and configuring virtualization in Windows Server
#### Step: 16 On the New Virtual Hard Disk pane, in the Size (GB) text box, type 5, leave other settings with their default values, and then select Create.

![notification](https://user-images.githubusercontent.com/39581053/165788854-3b629549-6eaf-4a1b-8079-2ce2ef2fce89.png)

Description of issue
Can't save the setting after creating the virtual disk. Appears to be a known error linked below. Work around suggests updating Storage Migration Service Extension to 1.113.0 or newer. The Lab currently has 2.15.0 installed by default.

Error is occurring on multiple Lab Instances of this profile.

https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#storage-migration-service-inventory-fails-with-a-parameter-cannot-be-found-that-matches-parameter-name-includedfsn

**Comment by TJGitHubUser** [comment]
Thanks for the heads up. We'll investigate and follow up.

**Comment by petender** [comment]
yes, the solution is to update the Storage Migration Service extension to at least version 1.113.0 in Windows Admin Center. The update should automatically appear in the feed and prompt for installation. To get there, go to the settings button in the upper right corner, select extensions, find the storage migration service in the list, and notice an update version number will be available. click update and wait a few seconds. From there, try again - tested earlier this morning in an AZ-800 delivery and fixed for all learners. Good luck.

**Comment by TJGitHubUser** [comment]
Thanks for rpviding this update Peter. We'll look to update the lab instructions once people have had a chance to implement this solution. Cheers.

**Comment by dvimacedo** [comment]
Issue doesn't manifest with the newer Windows Server version.
