### ISSUE TITLE
Lab 7: Typo

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#3]
## Lab/Demo: 07
Exercise 1
#### Step: 07

Description of issue

The lease is obtained from _SEA-SVR1_, not _SEA-SVR2_.  Given the previous DHCP installation steps use _SEA-SVR1_ it is presumed this is a typo and should be corrected to be _SEA-SVR1._ (but referenced IP is correct for SVR1)

**Comment by TJGitHubUser** [comment]
This has now been fixed (LAK also). Thank you
