### ISSUE TITLE
Lab 4: Deploy-WACAzVM.ps1 fails w/errors

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#4]
# Module: 00
#### Step: 08

Description of issue

**Deploy-WACAzVM.ps1** script will error at this point, preventing fully successful completion of the balance of the Lab:

![image](https://user-images.githubusercontent.com/49700217/154131882-85714e48-6fac-4135-8407-5e2325fc50f9.png)

Repro steps:

1. Follow lab to that point, as-written
2. Note that in Lab 4, Exercise 2, Task 2, Step 2: Instructions reference _sea-**svr2**.contoso.com_ however given context, and the VMs specified in the course manifest, this is likely a typo and the VM ought to be _sea-**adm1**.contoso.com_

Interestingly, the VM itself, and a variety of the resources *are* in fact, created successfully, however certain items (such as the DNS name) do not get populated.  You can log in to the VM using RDP and the Student account, but due to the errors seen in script it is uncertain what else may have failed.

Also, I realize this is a different course issue BUT - this is essentially the identical behavior seen in WS-012, in this still open/unfixed issue that appeared relatively recently in identical .ps1, used almost identically as it is in AZ-800:  https://github.com/MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS/issues/36

Because a suspiciously similar issue was seen with this very same Deploy-WACAzVM.ps1 script in yet one more past WS-012 issue (but was fixed ~April 7th, 2021) I feel it _might_ be productive to take a look at some of the various bug reports down that chain.  Apologies if these end up being red herrings - but the behaviors (relating to configuration of WSRemoting + forcing ignore of self-signed certs - are just so very similar to the behavior in the here and now for this AZ-800 error behavior.

See also:  https://github.com/MicrosoftDocs/azure-docs/issues/68262

I have tried using various previous versions of the   https://www.powershellgallery.com/packages/PSWSMan/2.3.0 module, and various other troubleshooting on this new AZ-800 issue but have as-yet been unsuccessful in understanding why we fail here.

**Comment by TesterTesterson1004** [comment]
Thanks very much, @garjam73, that solution seemed to work for the older ws-012 course, I will test it for this course now and hopefully same success!

**Comment by sotiris84** [comment]
I am also facing an issue with this specific step. I have followed [garjam73](https://github.com/garjam73) solution, but still receive the same error.

**Comment by Yiizo** [comment]
@garjam73 solution fixed the error @TesterTesterson1004 raised. However, I'm now encountering a new error.

![AZ-800M4 Error](https://user-images.githubusercontent.com/98825246/157469837-dc90517d-127d-4e2f-8dbc-879480ee16de.png)

Any recommended solutions?

**Comment by craigbeeremct** [comment]
@[Yiizo](https://github.com/Yiizo), I've seen that issue in another situation, caused by an error in the latest version of the PowerShell module. I found some instructions that talked about uninstalling Az.Compute and installing version 4.23.0. This sorted out the issue I was having on my machine, but didn't help in Cloud Shell because I couldn't uninstall the Az.Compute module due to modules using it that were required to run for Cloud Shell to operate. I gave up after a bit of time, so never got to the bottom of it.

See
https://github.com/Azure/azure-powershell/issues/17370
https://techcommunity.microsoft.com/t5/azure-virtual-desktop/azure-compute-gallery-quot-vmcustomization-is-not-enabled-for/m-p/3151871

**Comment by sotiris84** [comment]
@craigbeeremct You can temporarily downgrade the Az.Compute module version in Cloud Shell. The change is not persistent, so when you spin up a new instance of cloud shell the latest version of Az.Compute module will be used again. The process is extremely simple:
 
#install the required version
Install-Module -Name Az.Compute -Force -RequiredVersion 4.23.0

#reload the session so the new module is used
pwsh

#Verify the version is correct
Get-Module -Name Az.Compute 

Unless you click the X button to close the cloud shell, the 4.23.0 version will be used.

(I saw the above in a comment - I don't remember where - so credits not mine)

 Now to the problem at hand, while the above solution solved the VMCustomization issue, the script failed later. My solution up to this day is to manually do what the script does (and have my students do the same)

**Comment by garjam73** [comment]
@sotiris84 I just tried your step to downgrade the AZ.Compute module alongside my $scriptparams fix and with both together the lab script works

**Comment by craigbeeremct** [comment]
> @craigbeeremct You can temporarily downgrade the Az.Compute module version in Cloud Shell. 

Thank you for those steps, much appreciated.

**Comment by Paterpetri** [comment]
Thank you, everyone for the information.  After I downgraded the Az.Compute version in CloudShell and corrected the $scriptParams block above, the DNS name and some other items still did not get created successfully.  I was not able to resolve this, and so I had to skip Exercise 4, Task 1. Any advice?

**Comment by sotiris84** [comment]
@Paterpetri You can perform the steps manually.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull requests #15 and #19.

**Comment by rdantas9** [comment]
Is there any idea?

![image](https://user-images.githubusercontent.com/46678057/170400554-33ed553f-f01f-4778-9db4-7de993873285.png)

**Comment by sh8pe** [comment]
In the policy it is stated that the name of the VM is only allowing name = az800l04-vm0 and not as stated az800l04-vmwac. In the further tasks also there is a mixture of both vm-names, which must be cleaned up.

**Comment by dpapkin** [comment]
![image](https://user-images.githubusercontent.com/24426530/192543034-b5ce3337-d657-4353-a8b4-f2a66621ba82.png)

Seems like $pipname doesnt get populated

**Comment by TesterTesterson1004** [comment]
Regarding the LODS/Cloudslice version (wherein errors indicated VM az800l04-vmwac was blocked by ACP) ...that now appears to be fixed.

**Comment by dpapkin** [comment]
Hi,

it isnt fixed using cloudslice .

I tried this yesterday,  hence my replying to the issue

Suggestions ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bsaghir** [comment]
Any idea how to fix this problem?
![problem](https://user-images.githubusercontent.com/57598495/210910958-2c57a8c0-d73a-4590-b6fc-ed07506ceb2b.png)

**Comment by dpapkin** [comment]
![lab4Ex3task11fails](https://user-images.githubusercontent.com/24426530/211464751-6230ed2d-f325-4a4e-92ef-198022fd1854.png)


Having this error message. All my students have this error message

**Comment by sotiris84** [comment]
The problem seems to exist still. Most probably the issue lies with the policies in place on online lab hosts. What I do in my classes is to explain the script, but actually perform the steps manually either in advance or as a demo during class.

**Comment by bsaghir** [comment]
These two commands will allow to download the msi on the machine and to install it with a self-signed certificate. So the first method you connect directly on the machine in rdp, the second method you open a powershell window in admin and you copy the 2 commands. Or as said above via run command and powershell script. You check that each command is well passed.
Start-Process msiexec.exe -Wait - "/i $env:USERPROFILE\Downloads\WindowsAdminCenter.msi /qn /L*v log.txt REGISTRY_REDIRECT_PORT_80=1 SME_PORT=443 SSL_CERTIFICATE_OPTION=generate"

I think that some command in the script deploy are not available for the new version of azure.

**Comment by bsaghir** [comment]
in the script, there is the command invoke-azurevmcommand and this command has changed name with the new version of AZURE. The new name for this command is invoke-AzureVmRuncommand.

**Comment by dpapkin** [comment]
I modified the Deploy-WAVLVAzVN.ps1  and it gives  a different error now

**Comment by TJGitHubUser** [comment]
Thank you. We'll run this through our test process and update accordingly.

**Comment by v-asamim** [comment]
I tested Lab 4 twice, it works fine; I couldn't find any errors.
I also tested with the solution reported by @melvinporter, it works fine too.

The reported solution is: “Execute the following commands before running the ./Deploy-WACAzVM.ps1 script
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor
[Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12”

### Here are the lab screenshots. 

#### Tested with default instructions
![lab 4 reported error - reported error not found ](https://github.com/MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure/assets/111972688/2d0c5362-2fea-43d0-b95c-40173f47fe09)

 #### Tested reported solution
![lab 4 reported error - tested reported solution without any error](https://github.com/MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure/assets/111972688/2b1224a2-3fac-4611-943e-f7fcccec3a22)
