### ISSUE TITLE
Lab 6, 

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#44]
# Module: 06
#### Step: 03

Description of issue
Where it says "Open Azure Security Center link" it should say "Microsoft Defender for Cloud"

**Comment by v-asamim** [comment]
Hello @Franlusan, your request has been added to PR https://github.com/MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure/pull/51.

**Comment by TJGitHubUser** [comment]
updated
