### ISSUE TITLE
Lab1 localgroup administrators not found. Unable to add Ty to the group

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#49]
# Module: 01
#### Step: 09

Description of issue
*localgroup administrators not found** error when trying to add Ty to Administrators.

Get-localgroup doesnt not show this localgroup Administrators

Unable to create new local group Administrators either.

![image](https://user-images.githubusercontent.com/24426530/192131736-16b43526-86fd-486d-a6ce-aba0c045c198.png)

![image](https://user-images.githubusercontent.com/24426530/192132612-26e4860b-012e-4f2e-8e72-7a67ffc30d01.png)

Repro steps:

1.
1.
1.

**Comment by v-asamim** [comment]
Hello @dpapkin, this lab has been tested several times and the error has not recurred.
![image](https://user-images.githubusercontent.com/111972688/209347687-7a622470-1527-4779-8971-73b5f312b960.png)
