### ISSUE TITLE
Lab 8: Typo in VNET name?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#5]
# Module: 00
#### Step: 03/05

Description of issue

If we try and use 'az800l08-vnet**1**' as specified in Step 3, we get an error in Step 5 'a virtual network cannot be peered with itself'.  This must be a typo?  (if we change step 3 to be 'az800l08-vnet**0**', it works as expected.

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. We'll look at this and address as appropriate.

**Comment by garjam73** [comment]
looks like the intention is for vnet0 to be the hub network. so the step should be carried out on Vnet0
steps 3 and 4 should reference az800l08-vnet0

that would be the correct network design intent for this scenario.

**Comment by TJGitHubUser** [comment]
Agree this appears to be a typo and a pretty straightforward fix. Will commit the change end of the week so as to not interfere with any ongoing training deliveries. Thanks for the feedback

**Comment by TJGitHubUser** [comment]
Request for clarification: shouldn't step 2 also reference az800l08-vnet0 instead of az800l08-vnet1?

**Comment by garjam73** [comment]
Yes in lab 8 it’s 2&3 in lab 8_ak it’s 3&4

**Comment by TJGitHubUser** [comment]
This has now been fixed in lab 8 and lab 8_ak.
