### ISSUE TITLE
All instructions should mention Entra or Entra ID instead of Azure AD

### ISSUE THREAD

**Issue by dave-007** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#59]
# Module: 00
#### Step: 00

Description of issue
Naming was changed, but not updated in labs.

Repro steps:

1. Search the lab content for 'Entra', no results.
1.
1.

**Comment by v-asamim** [comment]
@dave-007 The lab contents have been updated with changes for Azure AD to Microsoft Entra ID.

**Comment by TJGitHubUser** [comment]
Fixed
