### ISSUE TITLE
Lab 9: Two issues, likely typo + recommended addition

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#6]
## Lab/Demo: 09

Description of issue

**Exercise 1, Task 2, Step 10**: says 'On the _sea-svr**1**.contoso.com_ page' but in context of the steps so far it seems like this must be a typo and should actually be 'On the _sea-svr**3**.contoso.com_ page'.

**Exercise 2, Task 2, Step 7:** This may be an idiosyncrasy of the VM speeds at the time I tested, but it might make sense to elaborate slightly on this step to indicate _'It may take some time before the Tasks/New iSCSI Virtual disk option becomes selectable'_.  It may be the first time the 'refresh' is run in this lab, it takes a lot longer then refreshes take later in the labs.  Later refreshes completed promptly.

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. We'll look into these and address as appropriate. Appreciate the suggestion re VM speeds for refresh.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #21.
