### ISSUE TITLE
Heading in Lab 8 don't show in menu bar online

### ISSUE THREAD

**Issue by autosysops** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#61]
# Module/Lab: 08
#### Step: 00

Description of issue

Only Exercise 3 shows in the online version of the lab.

Repro steps:

1. Go to https://microsoftlearning.github.io/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure/Instructions/Labs/LAB_08_Implementing_hybrid_networking_infrastructure.html
1.
1.

**Comment by TJGitHubUser** [comment]
Issue was fixed. Just need to close.
