### ISSUE TITLE
LAB_AK_04_Exercise 3_Task 1_"Deploy-WACAzVM.ps1 fails"

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#71]
# Module/Lab: 04
#### Step: 10

Encountered the following error again, even after completing the newly added steps to address it:
_"Invoke-Command:_ _This parameter set requires WSMan, and no supported WSMan client library was found. WSMan is either not installed or unavailable for this system._
_Write-Error: Ending installation of WAC on virtual machine az800l04-vmwac"_

![image](https://github.com/user-attachments/assets/615c2239-76d8-4900-90a1-4970d7101bff)

**Comment by dvimacedo** [comment]
deployed a workaround for the issue in a previous PR.
