### ISSUE TITLE
Lab 06, Exercise 2, Task 2 - warning about pasting code

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure#8]
Using the type text feature in the ALH will probably[^1] mess up the JSON code in the web browser. There needs to be the usual warning here.

AZ-104 uses the following phrasing.

Note: If you are using a tool that pastes the code in line by line intellisense may add extra brackets causing validation errors. You may want to paste the code into notepad first and then paste it into line 20.

[^1]: Skillable will _certainly_ mess up the code. I suspect other ALH's will do the same. :-)

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. Will add those to list of issues to address.

**Comment by TJGitHubUser** [comment]
Thanks for the feedback. We'll look into addressing this issue as appropriate.

**Comment by TJGitHubUser** [comment]
Added the note as suggested. Thank you.
